disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Frank Meléndez"
contentDir = "content/en" # no venia originalmente lo copie de mi conf

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "img/logo.png"
# secondaryLogo = "img/secondary-logo.png"
description = "With over six years in Business Intelligence and three in data science and machine learning, I have built dashboards, financial simulations, and risk analysis tools. Today I am developing an educational platform with personalized content and dynamic difficulty scaling, built on Linux and cloud-native architectures"
# copyright = "Copy, _right?_ :thinking_face:"

[params.author]
name = "Francisco Aguilar Meléndez"
#   email = "youremail@example.com"
image = "img/blowfish_logo.png"
#   imageQuality = 96
headline = "Data Scientist and ML/AI Engineer | Co-founder of an accessible and sustainable educational platform"
bio = "Data Scientist and ML/AI Engineer with experience in Business Intelligence and data science projects. Co-founder of an educational company, where I develop a lightweight and scalable platform aimed at democratizing access to learning."
links = [
  { email = "mailto:frank@frankmelendez.com" },
  { linkedin = "https://www.linkedin.com/in/fcoaguilarm" },
  # { github = "https://github.com/greenLogic" },
  # { hashnode = "https://crackerfrank.hashnode.dev/" },
  # { leetcode = "https://leetcode.com/u/greenLogic/" },
  # { kaggle = "https://www.kaggle.com/frankam" },
  # { huggingface = "https://huggingface.co/frankam" },
]
